FROM ubuntu:16.04
WORKDIR /yandextank
RUN apt-get update && \
    apt-get install -y python-pip
RUN pip install --upgrade setuptools
RUN pip install --upgrade pip
RUN pip install pytest
CMD pip install . && pytest -s